spring:
  application:
    name: fen_ku_fen_biao
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config.yaml

  # 配置 DataSource Driver
#  spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
  # 指定 YAML 配置文件
#  spring.datasource.url=jdbc:shardingsphere:classpath:xxx.yaml



